Repository FutureTense/lock-manager, pull requests merged in 2020-10, with the labels that each got.

#18 Create nb.json
  custom_components/lock-manager/translations/nb.json
Labels: translations

#19 Unified ozw and zwave update
  custom_components/lock-manager/FrontDoor.ini
  custom_components/lock-manager/__init__.py
  custom_components/lock-manager/config_flow.py
  custom_components/lock-manager/const.py
  custom_components/lock-manager/lock_manager_common.yaml
  custom_components/lock-manager/strings.json
  custom_components/lock-manager/translations/en.json
Labels: bug fix

#20 Make the confirmation UI work completely
  custom_components/lock-manager/__init__.py
  custom_components/lock-manager/const.py
  custom_components/lock-manager/lock_manager.yaml
Labels: breaking change, bug fix

#22 Ozw version
  custom_components/lock-manager/__init__.py
  custom_components/lock-manager/const.py
  custom_components/lock-manager/lock_manager.yaml
Labels: bug fix

#26 adding documentation for required lovelace libraries
  README.md
Labels: documentation

#27 Add code slot sensors
  custom_components/lock-manager/__init__.py
  custom_components/lock-manager/const.py
  custom_components/lock-manager/sensor.py
Labels: enhancement

#32 Add zwave support
  custom_components/lock-manager/const.py
  custom_components/lock-manager/sensor.py
Labels: bug fix, enhancement

#33 Unified add/clear code services
  custom_components/lock-manager/__init__.py
  custom_components/lock-manager/const.py
  custom_components/lock-manager/sensor.py
  custom_components/lock-manager/services.yaml
Labels: bug fix, enhancement

#40 Refresh codes
  custom_components/lock-manager/__init__.py
  custom_components/lock-manager/lock_manager_common.yaml
  custom_components/lock-manager/services.yaml
Labels: bug fix

#41 Service adjustments
  custom_components/lock-manager/__init__.py
  custom_components/lock-manager/lock_manager_common.yaml
Labels: breaking change, bug fix

#43 Fix service calls
  custom_components/lock-manager/__init__.py
Labels: bug fix

#44 add images for wiki
  docs/integration_screen_wiki.png
Labels: documentation

#49 Fix code slot erros
  custom_components/lock-manager/const.py
  custom_components/lock-manager/sensor.py
Labels: bug fix

#50 Add sensor availablility
  custom_components/lock-manager/sensor.py
Labels: enhancement

#51 Stop blocking zwave users
  custom_components/lock-manager/__init__.py
Labels: bug fix

#53 More zwave testing
  custom_components/lock-manager/lock_manager_common.yaml
  custom_components/lock-manager/sensor.py
Labels: bug fix
